const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('antiRecAPI', {
  navigate: (url) => ipcRenderer.send('app-navigate', url),
  reload: () => ipcRenderer.send('app-reload'),
  setAlwaysOnTop: (isTop) => ipcRenderer.send('app-set-always-on-top', isTop),
  minimize: () => ipcRenderer.send('app-minimize'),
  hide: () => ipcRenderer.send('app-hide'),
  setPrompt: (prompt) => ipcRenderer.send('app-set-prompt', prompt),
  clearSession: () => ipcRenderer.send('app-clear-session'),
  setOpacity: (val) => ipcRenderer.send('app-set-opacity', val),
  setAntiObs: (val) => ipcRenderer.send('app-set-antiobs', val),
  saveSettings: (settings) => ipcRenderer.send('app-save-settings', settings),
  getSettings: () => ipcRenderer.invoke('app-get-settings'),
  getVersion: () => ipcRenderer.invoke('app-get-version'),
  checkUpdate: () => ipcRenderer.invoke('app-check-update'),
  openExternal: (url) => ipcRenderer.send('app-open-external', url),
  onSettingsOpened: (isOpen) => ipcRenderer.send('app-settings-opened', isOpen),
  onSiteChanged: (callback) => ipcRenderer.on('site-changed', (_event, site) => callback(site)),
  onInitialSettings: (callback) => ipcRenderer.on('initial-settings', (_event, settings) => callback(settings)),
  downloadUpdate: () => ipcRenderer.invoke('app-download-update'),
  installUpdate: () => ipcRenderer.send('app-install-update'),
  onUpdaterStatus: (callback) => ipcRenderer.on('updater-status', (_event, data) => callback(data)),
  onUpdaterProgress: (callback) => ipcRenderer.on('updater-progress', (_event, data) => callback(data)),
  setGhostMode: (val) => ipcRenderer.send('app-set-ghost-mode', val),
  toggleGhostMode: () => ipcRenderer.send('app-toggle-ghost-mode'),
  onGhostModeChanged: (callback) => ipcRenderer.on('ghost-mode-changed', (_event, isGhost) => callback(isGhost)),
  finishInteractiveSnip: (bounds) => ipcRenderer.send('app-finish-interactive-snip', bounds),
  cancelInteractiveSnip: () => ipcRenderer.send('app-cancel-interactive-snip')
});
